# See https://pre-commit.com for more information
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: check-toml
- repo: https://github.com/python-poetry/poetry
  rev: '1.5.1'
  hooks:
    - id: poetry-check
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.1.3'
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.3
  hooks:
    - id: ruff-format
