version: '3.9'

services:
  slowking-api-eventbus:
    build: .
    container_name: slowking-api-eventbus
    command: api
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST?Variable not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?Variable not set}
    volumes:
      - ./src:/home/app/src
    ports:
      - 8091:8091
    restart: on-failure
    depends_on:
      - postgres
      - redis
      - slowking-event-consumer

  slowking-event-consumer:
    build: .
    container_name: slowking-event-consumer
    command: event-consumer
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST?Variable not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?Variable not set}
      REDIS_HOST: ${REDIS_HOST?Variable not set}
      REDIS_PORT: ${REDIS_PORT?Variable not set}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./src:/home/app/src

  redis:
    container_name: slowking-redis-broker
    image: redis:7
    restart: always
    command: --port 63791
    ports:
      - 63791:63791

  postgres:
    image: postgres:15.3
    container_name: slowking-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB?Variable not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?Variable not set}
      POSTGRES_USER: ${POSTGRES_USER?Variable not set}
    ports:
      - "54321:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  slowking-api-eventbus:
  slowking-api-event-consumer:
  redis:
  postgres:
