version: '3.9'

services:
  slowking-api-eventbus:
    build: .
    container_name: slowking-api-eventbus
    command: api
    volumes:
      - ./src:/home/app/src
    ports:
      - 8091:8091
    restart: on-failure
    depends_on:
      - redis
      - slowking-event-consumer

  slowking-event-consumer:
    build: .
    container_name: slowking-event-consumer
    command: event-consumer
    depends_on:
      - redis
    environment:
      REDIS_HOST: "slowking-redis-broker"
      REDIS_PORT: 63791
    volumes:
      - ./src:/home/app/src

  redis:
    container_name: slowking-redis-broker
    image: redis:7
    restart: always
    command: --port 63791
    ports:
      - 63791:63791

volumes:
  slowking-api-eventbus:
  slowking-api-event-consumer:
  redis:
