version: '3.9'

services:
  slowking-api-eventbus:
    build: .
    container_name: slowking-api-eventbus
    command: api
    env_file:
      - .env
    environment:
      DB_HOST: ${SLOWKING_DB_HOST?Variable not set}
      POSTGRES_PASSWORD: ${SLOWKING_POSTGRES_PASSWORD?Variable not set}
    volumes:
      - ./slowking:/home/app/slowking
    ports:
      - 8091:8091
    restart: on-failure
    depends_on:
      - slowking-postgres
      - slowking-redis
      - slowking-event-consumer
    # networks:
    #   - network_eigen_dev

  slowking-event-consumer:
    build: .
    container_name: slowking-event-consumer
    command: event-consumer
    env_file:
      - .env
    environment:
      DB_HOST: ${SLOWKING_DB_HOST?Variable not set}
      POSTGRES_PASSWORD: ${SLOWKING_POSTGRES_PASSWORD?Variable not set}
      REDIS_HOST: ${SLOWKING_REDIS_HOST?Variable not set}
      REDIS_PORT: ${SLOWKING_REDIS_PORT?Variable not set}
    depends_on:
      - slowking-postgres
      - slowking-redis
      - mailhog
    volumes:
      - ./slowking:/home/app/slowking
      - ./reports:/home/app/reports
    # networks:
    #   - network_eigen_dev

  slowking-redis:
    container_name: slowking-redis-broker
    image: redis:7
    restart: always
    command: --port 63791
    ports:
      - 63791:63791
    # networks:
    #   - network_eigen_dev

  slowking-postgres:
    image: postgres:15.3
    container_name: slowking-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${SLOWKING_POSTGRES_DB?Variable not set}
      POSTGRES_PASSWORD: ${SLOWKING_POSTGRES_PASSWORD?Variable not set}
      POSTGRES_USER: ${SLOWKING_POSTGRES_USER?Variable not set}
      PGPORT: ${SLOWKING_DB_PORT?Variable not set}
    ports:
      - "54322:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    # networks:
    #   - network_eigen_dev

  eigenapi:
    build:
      context: ./eigenapi
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: eigenapi
    ports:
      - "8283:8283"
    volumes:
      - ./eigenapi:/home/app/src

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: slowking-mailhog
    ports:
      - "11025:1025"
      - "18025:8025"

# networks:
#   network_eigen_dev:
#     name: eigen_dev_default
#     external: true

volumes:
  slowking-api-eventbus:
  slowking-api-event-consumer:
  slowking-redis:
  slowking-postgres:
  eigenapi:
