# https://taskfile.dev
version: '3'

tasks:
  default:
    desc: Build and run the application
    cmds:
      - task: build
      - task: up

  build:
    desc: Build the application via docker-compose
    cmds:
      - docker-compose build

  up:
    desc: Run the application via docker-compose
    cmds:
      - docker-compose up

  start:
    desc: Make a request to the application using HTTPie to start a benchmark
    cmds:
      - http POST localhost:8091/api/v1/benchmarks/start @./tests/data/payload.json

  event:
    desc: Make a request to the application using HTTPie with a test event
    cmds:
      - http POST localhost:8091/api/v1/events/publish @./tests/data/event.json

  local-env:
    desc: Create local virtual environment
    internal: true
    cmds:
      - python3 -m venv .venv

  install:
    desc: Install dependencies (locally, not in Docker)
    cmds:
      - task: local-env
      - source .venv/bin/activate
      - poetry install
      - pre-commit install

  fmt:
    desc: "Formats code using ruff and black"
    cmds:
      - ruff --fix .
      - black .

  test:
    desc: Run tests (locally, not in Docker)
    cmds:
      - source .venv/bin/activate
      - pytest -vv
