name: CI

# TODO replace once all working
on: [push, pull_request]
# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Run image
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: 1.5.1
    - name: Install Taskfile
      uses: arduino/setup-task@v1
      with:
        version: 3.x
        # repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install dependencies
      run: poetry install
    - name: Lint and format check
      run: task fmt-check
    - name: Test with pytest
      run: task test
